exclude: [Gemfile, Gemfile.lock, CNAME, readme.md]
time_zone: America/Detroit
encoding: utf-8
show_drafts: true
permalink: pretty
repository: shreve/shreve.github.io

collections:
  recipes:
    output: true
    permalink: /:collection/:title

defaults:
  -
    scope:
      path: ''
    values:
      layout: page

  -
    scope:
      type: 'recipes'
    values:
      layout: recipe
